// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface IDiceCheck { result: number, rate_of_success: number, dice_against: string, }