// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDiceSanLoss } from "./IDiceSanLoss";

export interface IDiceSanCheck { san_check: number, san_loss: IDiceSanLoss, }