// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDiceCheck } from "./IDiceCheck";
import type { IDiceNaive } from "./IDiceNaive";
import type { IDiceSanCheck } from "./IDiceSanCheck";

export type IDiceResult = { "DiceNaive": IDiceNaive } | { "DiceCheck": IDiceCheck } | { "DiceSanCheck": IDiceSanCheck };