// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDiceResult } from "./IDiceResult";

export interface IDice { tx_id: number, result: IDiceResult, command: string, }