// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ITxAction } from "./ITxAction.d";

export type ITxAux = { tx_id: bigint, raw_id: bigint, stage: String, user: String, avatar: String, time: String, action: ITxAction, };
