// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IAvatarAux } from "../avatar/IAvatarAux.d";
import type { IRolePlay } from "./IRolePlay.d";

export type ITxAction = { "RolePlay": IRolePlay } | { "AvatarAdd": IAvatarAux } | { "AvatarDel": IAvatarAux } | { "AvatarModify": [IAvatarAux, IAvatarAux] };
