// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDetail } from "../avatar/IDetail.d";
import type { IRolePlay } from "./IRolePlay.d";

export type ITxAction = { "RolePlay": IRolePlay } | { "AvatarAdd": [string, IDetail] } | { "AvatarDel": [string, IDetail] } | { "AvatarModify": [string, IDetail, IDetail] };
