// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IAvatarDetail } from "../avatar/IAvatarDetail.d";
import type { IRolePlay } from "./IRolePlay.d";

export type ITxAction = { "RolePlay": IRolePlay } | { "AvatarAdd": [string, IAvatarDetail] } | { "AvatarDel": [string, IAvatarDetail] } | { "AvatarModify": [string, IAvatarDetail, IAvatarDetail] };
