// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IStageRule } from "../../../entity/basic/IStageRule.d";

export type IReqCreateStage = { title: string, description: string, rule: IStageRule, };
