// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ITxAction } from "../../../entity/tx/ITxAction.d";

export type ITxEvent = { raw_id: string, tx_index: number, stage_id: string, user_id: string, avatar_id: string, time: String, action: ITxAction, };
