// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IExtraEffect } from "./IExtraEffect.d";

export type IWeaponDamage = { dice: string, side_effect: IExtraEffect | null, };
