// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDetail } from "./avatar/IDetail";

export type IAvatar = { id: number, stage_id: number | null, owner: number, name: string, detail: IDetail, header: string | null, };
