// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ICustomEquipment } from "./ICustomEquipment";
import type { IWeapon } from "./weapon/IWeapon";

export type IEquipmentItem = { "Weapon": IWeapon } | { "Custom": ICustomEquipment };