// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IArea } from "../IArea";

export type IGameMap = { uuid_to_area: { [key in string]?: IArea }, };
