// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IArea } from "./IArea";

export interface IGameMap { uuid_to_area: Record<string, IArea>, }