// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IGameMap } from "./IGameMap";

export interface IStage { uuid: string, owner: number, title: string, description: string, area: IGameMap, }