[package]
name = "coc-dan-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
mock = ["surrealdb/kv-mem"]  # run test on mock db

[dependencies]
tokio = { version = "*", features = ["full"] }
futures = "*"
tracing = "0.1"
tracing-subscriber = "*"
serde = "1"
serde_json = "*"
axum = { version = "*", features = ["json", "ws" ] }
axum-extra = { version = "*", features = ["cookie"] }
http = "1.1"
uuid = { version = "1.11.0", features = ["v4"] }
dotenvy = "0.15"
rand = "0.8"
chrono = { version = "*", features = ["std"] }
surrealdb = { version = "2.0.4" }
surrealdb-core = "2.0.4"
async-trait = "0.1"
thiserror = "1"
ts-rs = "10.0.0"
axum-test = "16.3.0"
