// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDetail } from "../../../entity/avatar/IDetail.d";
import type { ITxEvent } from "../../ws/tx/ITxEvent.d";

export type IGameStateFragment = { begin_tx_index: number, end_tx_index: number, stage_id: string, avatars: { [key in string]?: IDetail }, logs: Array<ITxEvent>, };
