// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IReqFetchGameStateFragment = { 
/**
 * end of the transaction id (exclusive)
 */
end_tx_index: number | null, 
/**
 * number of logs
 */
count: number, };
