// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDetail } from "../../../entity/avatar/IDetail.d";

export type IReqUpdateAvatar = { raw_id: string, detail: IDetail, };
