// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDetail } from "./IDetail.d";

export type IAvatarAux = { raw_id: string, stage: String, owner: String, name: string, detail: IDetail, header: string, creation_time: Option<String>, last_update_time: Option<String>, };
