// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ICharacteristics } from "./ICharacteristics.d";
import type { IDescriptor } from "./IDescriptor.d";
import type { IEquipment } from "./IEquipment.d";
import type { IOccupation } from "./IOccupation.d";
import type { ISkillAssigned } from "./ISkillAssigned.d";
import type { IStatus } from "./IStatus.d";

export type IAvatarDetail = { name: string, header: string, status: IStatus, characteristics: ICharacteristics, basic_info: IDescriptor, skills: { [key in string]?: ISkillAssigned }, occupation: IOccupation, equipments: Array<IEquipment>, };
