// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDetail } from "./IDetail.d";

export type IAvatarAux = { raw_id: string, stage_id: bigint, owner_id: bigint, name: string, detail: IDetail, creation_time: string | null, last_update_time: string | null, };
