// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IAvatarDetail } from "./IAvatarDetail.d";
import type { IStage } from "../basic/IStage.d";
import type { IUser } from "../basic/IUser.d";

export type IAvatar = { raw_id: string, stage: IStage, owner: IUser, version: IAvatarDetail, creation_time: string | null, };
