// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IEquipmentItem } from "./IEquipmentItem.d";

export type IEquipment = { name: string, item: IEquipmentItem, };
