// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ICharacteristicEnum } from "./ICharacteristicEnum.d";
import type { IEraEnum } from "../basic/IEraEnum.d";
import type { IOccupationalSkill } from "../skill/IOccupationalSkill";

export type IOccupation = { name: string, credit_rating: [number, number], era: IEraEnum, characteristics: Array<ICharacteristicEnum>, occupational_skills: Array<IOccupationalSkill>, };
