// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IEraEnum } from "../basic/IEraEnum.d";
import type { ISkillCategory } from "../skill/ISkillCategory.d";

export type ISkillAssigned = { name: string, initial: number, era: IEraEnum, occupation_skill_point: number, interest_skill_point: number, category: ISkillCategory, assign_type: number, };
