
@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

### Login
# @name login
POST http://{{host}}/api/user/login HTTP/1.1
Content-Type : application/json

{
    "name" : "ruffnex"
}

@cookies = {{login.response.headers.set-cookie}}



### create stage
# @name new_stage
POST http://{{host}}/api/stage/new HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

{
    "title" : "stage title",
    "description" : "example stage"
}

@stage_uuid = {{new_stage.response.body.uuid}}



### create an avatar
# @name new_avatar
POST http://{{host}}/api/avatar/new HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

{
    "name" : "new avatar",
    "description" : "new avatar",
    "stage_id" : "{{stage_uuid}}"
}

@avatar_id = {{new_avatar.response.body.id}}



### get avatar by id
GET http://{{host}}/api/avatar/{{avatar_id}} HTTP/1.1
Cookie: {{cookies}}


### list all my avatars
GET http://{{host}}/api/avatar/list_owned HTTP/1.1
Cookie: {{cookies}}


### delete an avatar
DELETE http://{{host}}/api/avatar/{{avatar_id}} HTTP/1.1
Cookie: {{cookies}}

### get a deleted avatar
GET http://{{host}}/api/avatar/{{avatar_id}} HTTP/1.1
Cookie: {{cookies}}

### create a new avatar
# @name new_avatar_2
POST http://{{host}}/api/avatar/new HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

{
    "name" : "new avatar",
    "description" : "new avatar",
    "stage_id" : "{{stage_uuid}}"
}

### leave stage 
POST http://{{host}}/api/stage/{{stage_uuid}}/leave
Cookie: {{cookies}}


### once you leave a stage, all avatars on this stage will be removed
GET http://{{host}}/api/avatar/{{new_avatar_2.response.body.id}} HTTP/1.1
Cookie: {{cookies}}


### logout
POST http://{{host}}/api/user/logout HTTP/1.1
Cookie: {{cookies}}
