// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDetail } from "../../../entity/avatar/IDetail.d";

export type IReqCreateAvatar = { stage_id: bigint, name: string, detail: IDetail, header: string | null, };
