// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IEraEnum } from "../basic/IEraEnum.d";
import type { ISkillCategory } from "./ISkillCategory.d";

export type ISkill = { name: string, initial: number, era: IEraEnum, category: ISkillCategory, };
