// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDetail } from "../IDetail";

export type ICreateAvatar = { name: string, detail: IDetail | null, stage_id: number | null, };
