// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IAttrsEnum = "str" | "dex" | "pow" | "con" | "app" | "edu" | "siz" | "int" | "mov" | "luk";