// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ICharacteristics { str: number, dex: number, pow: number, con: number, app: number, edu: number, siz: number, int: number, mov: number, luk: number, mov_adj: number | null, }