// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IGender } from "./IGender";

export interface IDescriptor { age: number, gender: IGender, homeland: string, }