// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface IDescriptor { age: number, career: string, gender: string, homeland: string, }