// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IAttrs } from "./IAttrs";
import type { IDescriptor } from "./IDescriptor";
import type { IOccupation } from "./IOccupation";
import type { ISkillAssigned } from "./ISkillAssigned";
import type { IStatus } from "./IStatus";

export interface IDetail { status: IStatus, attrs: IAttrs, descriptor: IDescriptor, skills: Record<string, ISkillAssigned>, occupation: IOccupation, }