// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IAttrsEnum } from "./IAttrsEnum";
import type { IEraEnum } from "../IEraEnum";
import type { IOccupationalSkill } from "./IOccupationalSkill";

export interface IOccupation { name: string, credit_rating: [number, number], era: IEraEnum, attribute: Array<IAttrsEnum>, occupational_skills: Array<IOccupationalSkill>, }