// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ISkillCategory } from "./ISkillCategory";

export interface IOptionalOccupationalSkill { category: ISkillCategory, candidates: Array<string>, limit: number, }