// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IEraEnum } from "../IEraEnum";
import type { ISkillAssignType } from "./ISkillAssignType";

export interface ISkillAssigned { name: string, initial: number, era: IEraEnum, occupation_skill_point: number, interest_skill_point: number, assign_type: ISkillAssignType, }