// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IEraEnum } from "../IEraEnum";

export interface ISkill { name: string, initial: number, era: IEraEnum, }