// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IHealthStatus } from "./IHealthStatus";
import type { IMentalStatus } from "./IMentalStatus";

export interface IStatus { hp: number, mp: number, san: number, hp_loss: number, mp_loss: number, san_loss: number, mental_status: IMentalStatus, health_status: IHealthStatus, }