// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IUser } from "./IUser.d";

export type ISession = { raw_id: string, login_time: string, expiration_time: string, session_type: { "User": IUser }, };
