// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IStageRule } from "./IStageRule.d";
import type { IUser } from "./IUser.d";

export type IStage = { raw_id: bigint, title: string, rule: IStageRule, description: string, owner: IUser, };
