// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IUser = { raw_id: string, username: string, nickname: string, active_status: "Active" | "Banned", registration_time: string, };
