// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IRolePlay } from "./tx_role_play.d";

export type ITxAction = { "RolePlay": IRolePlay };
