// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IAmmoCapacity } from "./IAmmoCapacity";
import type { IEraEnum } from "../IEraEnum";
import type { IWeaponDamage } from "./IWeaponDamage";
import type { IWeaponRange } from "./IWeaponRange";

export interface IWeapon { name: string, skill_name: string, damage: IWeaponDamage, range: IWeaponRange, penetration: boolean, rate_of_fire: number, ammo_capacity: IAmmoCapacity, reliability: number, era: IEraEnum, price: number, category: Array<string>, }