[package]
name = "coc-dan-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = { version = "0.2" }
serde-wasm-bindgen = { version = "0.6" }
js-sys = { version = "0.3" }
serde = "1"
http = "1"
ts-rs = "10"
lazy_static = "1"
serde_json = "*"
lalrpop-util = { version = "0.22", features = ["lexer"] }
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8.5", features = ["getrandom"]}
regex = { version="1", default-features = false, features = ["perf", "std", "unicode"] }

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
lalrpop = "0.22"
