ts:
    cargo test
    rm -rf ../coc-dan-frontend/src/bindings
    mv ./bindings ../coc-dan-frontend/src/
    cp ./resource/skills.json ../coc-dan-frontend/src/core/card/
    cp ./resource/occupation.json ../coc-dan-frontend/src/core/card/
    cp ./resource/weapons.json ../coc-dan-frontend/src/core/card/

wasm:
    wasm-pack build --target web
    rm -rf ./npm
    cp -r pkg npm