// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ITx } from "./ITx";

export interface ITransaction { id: number, tx_id: number, stage_uuid: string, user_id: number, time: string, tx: ITx, }