// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ITx } from "./ITx";

export interface ITransaction { tx_id: number, stage_id: number, user_id: number, avatar_id: number, time: string, tx: ITx, }