// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IAvatar } from "../IAvatar";
import type { IDice } from "../dice/IDice";

export type ITx = { "Statement": string } | { "Dice": IDice } | { "UpdateAvatar": { before: IAvatar | null, after: IAvatar | null, } };